### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Citiroller**
Fixes updating the data of fit objects.
This needs more work and some help would be appreciated.

Updating the data with a different shape and performing a fit works for:
- [x] xy (tested)
- [x] xy multi (needs testing)
- [x] indexed (needs testing)
- [x] unbinned (tested)
- [x] histogram (tested)

### CODE REVIEW

**Comment by JohannesGaessler** [comment]
In what timeframe would you need me to review this pull request?
I'm currently short on time and will probably only get to it in September.

**Comment by Citiroller** [comment]
You don't have to review it. It would be nice to get some feedback on how to handle this problem properly. But I'll ask @dsavoiu  tomorrow.

**Comment by Citiroller** [comment]
> In what timeframe would you need me to review this pull request?
> I'm currently short on time and will probably only get to it in September.

If you have some more time by now, it would be very nice if you could look into this issue for XY-Multi-Fits

**Comment by Citiroller** [comment]
This should all be working now.
Unit tests for changing the size of the new data for indexed and XYMultifit are still needed.
Please review the code, as this is a bigger change.

**Pull request merged**
