### PR TITLE
[WIP] Generic multifits rebased

### PR DESCRIPTION
**Pull request by JohannesGaessler**
This PR is a rebased version of https://github.com/dsavoiu/kafe2/pull/50 .
It is compatible with the changes made to the kafe2 `Nexus` as well as kafe2 plotting implemented by @dsavoiu .
@Citiroller please verify if this version works correctly with your use case.

Compared to the original PR this one does not implement a `CombinedNexus(Nexus)` object.
Instead it implements a `Nexus.source_from(other_nexus)` method that adds the nodes of one `Nexus` object to another `Nexus` object.
Note that these are the exact same nodes rather than copies.

### CODE REVIEW

**Comment by Citiroller** [comment]
The current version does not work for my case with two Histograms:
```
/home/cverstege/src/kafe2/kafe2/fit/histogram/model.py:138: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  _int_val[_i], _ = integrate.quad(_integrand_func, _a, _b)
/home/cverstege/.virtualenvs/kafe2_py3/lib/python3.6/site-packages/scipy/stats/_discrete_distns.py:517: RuntimeWarning: invalid value encountered in greater_equal
  return mu >= 0
/home/cverstege/src/kafe2/kafe2/core/minimizers/iminuit_minimizer.py:152: HesseFailedWarning: HESSE Failed. Covariance and GlobalCC will not be available
  self._get_iminuit().hesse()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/cverstege/opt/pycharm-2019.1.3/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/cverstege/opt/pycharm-2019.1.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/cverstege/src/kafe2/examples/999_Bachelor/lande_factor.py", line 59, in <module>
    lande.do_fit()
  File "/home/cverstege/src/kafe2/examples/999_Bachelor/lande_factor.py", line 49, in do_fit
    self.fit_multi.do_fit()
  File "/home/cverstege/src/kafe2/kafe2/fit/multi/fit.py", line 211, in do_fit
    self._update_singular_fits()
  File "/home/cverstege/src/kafe2/kafe2/fit/multi/fit.py", line 88, in _update_singular_fits
    parameter_cor_mat=self.parameter_cor_mat[_parameter_indices][:, _parameter_indices],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Citiroller** [comment]
When commenting out this line, the same happens for the cov_mat one line after this.

**Comment by JohannesGaessler** [comment]
The problem is that the fitter returns `None` as the parameter covariance matrix.
As a consequence both the correlation matrix and the covariance matrix are `None`

**Comment by JohannesGaessler** [comment]
PR was merged as-is to provide a tag for the thesis of @Citiroller

**Pull request merged**
